import React from "react";
import { Link } from "react-router-dom";
import { User, Plane, Sparkles, Wallet, Briefcase } from "lucide-react";
import Footer from "../components/Footer.jsx";
import GlobeComponent from "../components/Globe.jsx";
import Navbar from "../components/Navbar.jsx";

const Home = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-white via-purple-50 to-purple-100">
      <Navbar />

      {/* Hero section */}

      <section className="max-w-7xl mx-auto px-5 lg:px-8 py-12 lg:py-16 overflow-hidden">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* LEFT */}

          <div className="order-2 lg:order-1">
            <p className="uppercase tracking-[5px] text-purple-600 text-xs md:text-sm font-semibold mb-5">
              AI Powered Travel Planner
            </p>

            <h1 className="text-4xl md:text-5xl lg:text-[62px] font-extrabold leading-tight text-gray-900">
              Your Dream Trip,
              <br />
              <span className="text-purple-700 inline-flex items-center gap-3">
                Planned by AI
                <Sparkles className="text-yellow-400" size={34} />
              </span>
            </h1>

            <p className="mt-7 text-gray-600 text-base md:text-lg leading-8 max-w-lg">
              Tell us your destination, travel budget, interests and trip
              duration.
              <br />
              <br />
              Our AI instantly creates a personalized travel itinerary specially
              designed according to your preferences.
            </p>

            <Link
              to="/login"
              className="inline-flex items-center gap-3 mt-9 bg-purple-700 hover:bg-purple-800 duration-300 text-white px-6 py-3 rounded-xl shadow-lg text-base font-medium"
            >
              <User size={18} />
              Log In To Get Started
            </Link>
          </div>

          {/* RIGHT */}

          <div className="relative flex justify-center order-1 lg:order-2">
            {/* Purple Glow */}

            <div className="absolute w-96 h-96 bg-purple-200 blur-[120px] opacity-50 rounded-full"></div>

            {/* Decorative Dot */}

            <div className="hidden lg:block absolute -top-5 right-16 w-4 h-4 bg-purple-300 rounded-full"></div>

            <div className="hidden lg:block absolute bottom-6 left-5 w-5 h-5 bg-purple-300 rounded-full"></div>

            <div className="relative flex justify-center order-1 lg:order-2">

    <div className="absolute w-96 h-96 bg-purple-200 blur-[120px] opacity-40 rounded-full"></div>

    <GlobeComponent />

</div>
          </div>
        </div>
      </section>
      {/* ================= FEATURES ================= */}

      <section className="max-w-7xl mx-auto px-5 lg:px-8 pb-16">
        <div className="grid md:grid-cols-3 gap-6">
          {/* Card 1 */}

          <div className="bg-white rounded-3xl p-7 shadow-lg hover:shadow-2xl duration-300">
            <div className="w-16 h-16 rounded-2xl bg-purple-100 flex items-center justify-center mb-5">
              <Sparkles className="text-purple-700" size={30} />
            </div>

            <h2 className="text-xl font-bold text-gray-900">
              AI Generated Itinerary
            </h2>

            <p className="mt-3 text-gray-600 leading-7">
              Get a complete travel itinerary generated by AI according to your
              destination, interests, duration and budget.
            </p>
          </div>

          {/* Card 2 */}

          <div className="bg-white rounded-3xl p-7 shadow-lg hover:shadow-2xl duration-300">
            <div className="w-16 h-16 rounded-2xl bg-purple-100 flex items-center justify-center mb-5">
              <Briefcase className="text-purple-700" size={30} />
            </div>

            <h2 className="text-xl font-bold text-gray-900">
              Smart Travel Planning
            </h2>

            <p className="mt-3 text-gray-600 leading-7">
              Plan your vacation within seconds instead of spending hours
              searching for places, activities and routes.
            </p>
          </div>

          {/* Card 3 */}

          <div className="bg-white rounded-3xl p-7 shadow-lg hover:shadow-2xl duration-300">
            <div className="w-16 h-16 rounded-2xl bg-purple-100 flex items-center justify-center mb-5">
              <Wallet className="text-purple-700" size={30} />
            </div>

            <h2 className="text-xl font-bold text-gray-900">
              Budget Friendly Trips
            </h2>

            <p className="mt-3 text-gray-600 leading-7">
              Every trip is planned keeping your maximum budget in mind with
              approximate costs for activities.
            </p>
          </div>
        </div>
      </section>

      {/* ================= FOOTER ================= */}

      <Footer />
    </div>
  );
};

export default Home;
